### ISSUE TITLE
HCAS - Structure Not Compliant

### ISSUE THREAD

**Issue by akeslo** [tholgir/TodoIst-Task-List#3]
![image](https://user-images.githubusercontent.com/3003773/103490559-b1773e00-4dea-11eb-8d03-bb6db65d6f7d.png)

**Comment by tholgir** [comment]
@akeslo could you check if it works for you now? I was not quite sure how the HACS integration worked and it seems I still needed to add a new github release that included the hacs.json file.

**Comment by akeslo** [comment]
@tholgir working perfectly now! Thank you!
