### ISSUE TITLE
URL on Click

### ISSUE THREAD

**Issue by akeslo** [tholgir/TodoIst-Task-List#4]
Is it possible to call action on this card? I can't seem to get the below to work, thank you!

my intent is to enable a shortcut off the card to the todoist site

```
type: 'custom:todoist-task-list'
title: Todoist (Due Today)
entity: calendar.due_today
action:
 service: url
 url_path: https://todoist.com
style: |
  ha-card {
  {% if is_state('calendar.due_today', 'off') %}
    display: none
  {% else %}
    background-color: #E44332;
    color: black;
  {% endif %}

```

**Comment by tholgir** [comment]
I had a look on how this works on other cards and this is not something that is supported by this card. You can always use a weblink to add a simple link to the todoist site.
