### ISSUE TITLE
Bullet point and comma

### ISSUE THREAD

**Issue by yinka** [tholgir/TodoIst-Task-List#5]
Thank you for this custom add-on.

I have 1 issue and 1 enhancement request if it's ok.

**_Issue_**: 
If I have a comma in my task, it will be interpreted as 2 separate tasks - i.e displayed on two lines
eg `buy stamp, £10 worth of stamps` will be rendered as           
- `buy stamp`
- `£10 worth of stamps`
 
**_Request_**: 
Could you please add bullets to the beginning of each tasks please, so that 
  ` buy stamp, £10 worth of stamps` then becomes:
`• buy stamp, £10 worth of stamps`

Thank you.

**Comment by tholgir** [comment]
@yinka sorry it took a while but I had some issues with testing modified code while using HACS but I think I fixed the bug. Could you test if you update to v1.1.1 if this fixes your problem?

Concerning the enhancement, I'll gonna try some things on how to improve the display but no guarantees.

**Comment by yinka** [comment]
Hi @tholgir 

I can confirm the bug is fixed in 1.1.1. Thanks for looking into it

**Comment by tholgir** [comment]
ok thanks for the feedback. i'll close the issue then .
